# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyCode.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pyCode(object):
    def setupUi(self, pyCode):
        pyCode.setObjectName("pyCode")
        pyCode.resize(912, 612)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/icon/logo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        pyCode.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(pyCode)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbox1 = QtWidgets.QGroupBox(self.widget)
        self.gbox1.setMinimumSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(16)
        self.gbox1.setFont(font)
        self.gbox1.setObjectName("gbox1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbox1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label1 = QtWidgets.QLabel(self.gbox1)
        self.label1.setObjectName("label1")
        self.horizontalLayout_2.addWidget(self.label1)
        self.codeword = QtWidgets.QLineEdit(self.gbox1)
        self.codeword.setMinimumSize(QtCore.QSize(100, 0))
        self.codeword.setObjectName("codeword")
        self.horizontalLayout_2.addWidget(self.codeword)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.gbox1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.code39 = QtWidgets.QRadioButton(self.groupBox_2)
        self.code39.setObjectName("code39")
        self.verticalLayout_3.addWidget(self.code39)
        self.code128 = QtWidgets.QRadioButton(self.groupBox_2)
        self.code128.setObjectName("code128")
        self.verticalLayout_3.addWidget(self.code128)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.gridLayout_2.setColumnStretch(1, 1)
        self.verticalLayout_2.addWidget(self.gbox1)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setMinimumSize(QtCore.QSize(0, 60))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout.setObjectName("gridLayout")
        self.image = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap(":/pic/temp/unnamed.jpg"))
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 3)
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(100, 500))
        self.groupBox.setTitle("")
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_2.setObjectName("formLayout_2")
        self.generate = QtWidgets.QPushButton(self.groupBox)
        self.generate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.generate.setCheckable(False)
        self.generate.setObjectName("generate")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.generate)
        self.download = QtWidgets.QPushButton(self.groupBox)
        self.download.setObjectName("download")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.download)
        self.horizontalLayout.addWidget(self.groupBox, 0, QtCore.Qt.AlignTop)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.SpanningRole, self.horizontalLayout)
        pyCode.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pyCode)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 912, 21))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        self.menu_4 = QtWidgets.QMenu(self.menubar)
        self.menu_4.setObjectName("menu_4")
        pyCode.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pyCode)
        self.statusbar.setObjectName("statusbar")
        pyCode.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(pyCode)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 0))
        self.toolBar.setCursor(QtGui.QCursor(QtCore.Qt.WhatsThisCursor))
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        pyCode.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.lang = QtWidgets.QAction(pyCode)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/icon/lingua.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.lang.setIcon(icon1)
        self.lang.setObjectName("lang")
        self.editcopy = QtWidgets.QAction(pyCode)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(":/pic/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.editcopy.setIcon(icon2)
        self.editcopy.setObjectName("editcopy")
        self.editcut = QtWidgets.QAction(pyCode)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/icon/cut.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.editcut.setIcon(icon3)
        self.editcut.setObjectName("editcut")
        self.editpaste = QtWidgets.QAction(pyCode)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/icon/paste.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.editpaste.setIcon(icon4)
        self.editpaste.setObjectName("editpaste")
        self.insert = QtWidgets.QAction(pyCode)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/pic/icon/new.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.insert.setIcon(icon5)
        self.insert.setObjectName("insert")
        self.help2 = QtWidgets.QAction(pyCode)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/pic/icon/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.help2.setIcon(icon6)
        self.help2.setObjectName("help2")
        self.about = QtWidgets.QAction(pyCode)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/pic/icon/information.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/pic/icon/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.about.setIcon(icon7)
        self.about.setObjectName("about")
        self.controlz = QtWidgets.QAction(pyCode)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/pic/icon/key.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.controlz.setIcon(icon8)
        self.controlz.setObjectName("controlz")
        self.exit2 = QtWidgets.QAction(pyCode)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/pic/icon/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit2.setIcon(icon9)
        self.exit2.setObjectName("exit2")
        self.modify = QtWidgets.QAction(pyCode)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/pic/icon/pen.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.modify.setIcon(icon10)
        self.modify.setObjectName("modify")
        self.delete_2 = QtWidgets.QAction(pyCode)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/pic/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.delete_2.setIcon(icon11)
        self.delete_2.setObjectName("delete_2")
        self.reproduce = QtWidgets.QAction(pyCode)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(":/pic/icon/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reproduce.setIcon(icon12)
        self.reproduce.setObjectName("reproduce")
        self.invalid = QtWidgets.QAction(pyCode)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(":/pic/icon/garbage.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.invalid.setIcon(icon13)
        self.invalid.setObjectName("invalid")
        self.detail = QtWidgets.QAction(pyCode)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(":/pic/icon/prop.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.detail.setIcon(icon14)
        self.detail.setObjectName("detail")
        self.printer = QtWidgets.QAction(pyCode)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(":/pic/icon/printer.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.printer.setIcon(icon15)
        self.printer.setObjectName("printer")
        self.exporttoexcel = QtWidgets.QAction(pyCode)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(":/pic/icon/export.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exporttoexcel.setIcon(icon16)
        self.exporttoexcel.setObjectName("exporttoexcel")
        self.query = QtWidgets.QAction(pyCode)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(":/pic/icon/filefind.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.query.setIcon(icon17)
        self.query.setObjectName("query")
        self.qbe_select = QtWidgets.QAction(pyCode)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(":/pic/icon/file_q.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon18.addPixmap(QtGui.QPixmap(":/pic/icon/filefind.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.qbe_select.setIcon(icon18)
        self.qbe_select.setObjectName("qbe_select")
        self.qbe_save = QtWidgets.QAction(pyCode)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(":/pic/icon/file_w.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.qbe_save.setIcon(icon19)
        self.qbe_save.setObjectName("qbe_save")
        self.first = QtWidgets.QAction(pyCode)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(":/pic/icon/gobegin.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.first.setIcon(icon20)
        self.first.setObjectName("first")
        self.previous = QtWidgets.QAction(pyCode)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(":/pic/icon/prev.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.previous.setIcon(icon21)
        self.previous.setObjectName("previous")
        self.jump = QtWidgets.QAction(pyCode)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(":/pic/icon/balloon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.jump.setIcon(icon22)
        self.jump.setObjectName("jump")
        self.next = QtWidgets.QAction(pyCode)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(":/pic/icon/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.next.setIcon(icon23)
        self.next.setObjectName("next")
        self.last = QtWidgets.QAction(pyCode)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(":/pic/icon/goend.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.last.setIcon(icon24)
        self.last.setObjectName("last")
        self.key = QtWidgets.QAction(pyCode)
        self.key.setIcon(icon8)
        self.key.setObjectName("key")
        self.help = QtWidgets.QAction(pyCode)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(":/pic/icon/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.help.setIcon(icon25)
        self.help.setObjectName("help")
        self.exit = QtWidgets.QAction(pyCode)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(":/pic/icon/quit.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.exit.setIcon(icon26)
        self.exit.setObjectName("exit")
        self.menu_1.addAction(self.help2)
        self.menu_1.addAction(self.about)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.controlz)
        self.menu_1.addSeparator()
        self.menu_1.addAction(self.exit2)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_4.menuAction())
        self.toolBar.addAction(self.lang)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.editcopy)
        self.toolBar.addAction(self.editcut)
        self.toolBar.addAction(self.editpaste)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.insert)
        self.toolBar.addAction(self.modify)
        self.toolBar.addAction(self.delete_2)
        self.toolBar.addAction(self.reproduce)
        self.toolBar.addAction(self.invalid)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.detail)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.printer)
        self.toolBar.addAction(self.exporttoexcel)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.query)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.first)
        self.toolBar.addAction(self.previous)
        self.toolBar.addAction(self.jump)
        self.toolBar.addAction(self.next)
        self.toolBar.addAction(self.last)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.exit)

        self.retranslateUi(pyCode)
        QtCore.QMetaObject.connectSlotsByName(pyCode)
        pyCode.setTabOrder(self.generate, self.download)

    def retranslateUi(self, pyCode):
        _translate = QtCore.QCoreApplication.translate
        pyCode.setWindowTitle(_translate("pyCode", "BarCode產生器"))
        self.gbox1.setTitle(_translate("pyCode", "產生Barcode小工具"))
        self.label1.setText(_translate("pyCode", "輸入內容："))
        self.groupBox_2.setTitle(_translate("pyCode", "產生圖檔選擇"))
        self.code39.setText(_translate("pyCode", "Code39"))
        self.code128.setText(_translate("pyCode", "Code128"))
        self.generate.setText(_translate("pyCode", "產生"))
        self.download.setText(_translate("pyCode", "儲存"))
        self.menu_1.setTitle(_translate("pyCode", "畫面"))
        self.menu_2.setTitle(_translate("pyCode", "編輯"))
        self.menu_3.setTitle(_translate("pyCode", "資料"))
        self.menu_4.setTitle(_translate("pyCode", "瀏覽"))
        self.toolBar.setWindowTitle(_translate("pyCode", "toolBar"))
        self.lang.setText(_translate("pyCode", "語言"))
        self.lang.setShortcut(_translate("pyCode", "Ctrl+L"))
        self.editcopy.setText(_translate("pyCode", "資料複製"))
        self.editcopy.setToolTip(_translate("pyCode", "資料複製"))
        self.editcut.setText(_translate("pyCode", "資料剪下"))
        self.editcut.setToolTip(_translate("pyCode", "資料剪下"))
        self.editpaste.setText(_translate("pyCode", "資料貼上"))
        self.editpaste.setToolTip(_translate("pyCode", "資料貼上"))
        self.insert.setText(_translate("pyCode", "新增"))
        self.insert.setToolTip(_translate("pyCode", "[F1]建立資料"))
        self.insert.setShortcut(_translate("pyCode", "F1"))
        self.help2.setText(_translate("pyCode", "說明"))
        self.help2.setShortcut(_translate("pyCode", "Ctrl+H"))
        self.about.setText(_translate("pyCode", "程式資訊"))
        self.about.setToolTip(_translate("pyCode", "程式資訊"))
        self.controlz.setText(_translate("pyCode", "必要欄位"))
        self.controlz.setToolTip(_translate("pyCode", "必要欄位"))
        self.controlz.setShortcut(_translate("pyCode", "Ctrl+R"))
        self.exit2.setText(_translate("pyCode", "離開"))
        self.exit2.setShortcut(_translate("pyCode", "Esc"))
        self.modify.setText(_translate("pyCode", "更改"))
        self.modify.setToolTip(_translate("pyCode", "[u]修改資料"))
        self.modify.setShortcut(_translate("pyCode", "U"))
        self.delete_2.setText(_translate("pyCode", "刪除"))
        self.delete_2.setToolTip(_translate("pyCode", "[F2]刪除資料"))
        self.delete_2.setShortcut(_translate("pyCode", "F2"))
        self.reproduce.setText(_translate("pyCode", "複製"))
        self.reproduce.setToolTip(_translate("pyCode", "[c]複製目前資料"))
        self.reproduce.setShortcut(_translate("pyCode", "C"))
        self.invalid.setText(_translate("pyCode", "無效"))
        self.invalid.setToolTip(_translate("pyCode", "[x]使資料無效"))
        self.invalid.setShortcut(_translate("pyCode", "X"))
        self.detail.setText(_translate("pyCode", "單身"))
        self.detail.setToolTip(_translate("pyCode", "[b]編輯單身資料"))
        self.detail.setShortcut(_translate("pyCode", "B"))
        self.printer.setText(_translate("pyCode", "列印"))
        self.printer.setToolTip(_translate("pyCode", "[o]列印報表"))
        self.printer.setShortcut(_translate("pyCode", "P"))
        self.exporttoexcel.setText(_translate("pyCode", "匯出Excel"))
        self.exporttoexcel.setToolTip(_translate("pyCode", "[e]單身匯出Excel"))
        self.exporttoexcel.setShortcut(_translate("pyCode", "E"))
        self.query.setText(_translate("pyCode", "查詢"))
        self.query.setToolTip(_translate("pyCode", "[q]尋找資料"))
        self.query.setShortcut(_translate("pyCode", "Q"))
        self.qbe_select.setText(_translate("pyCode", "條件查詢"))
        self.qbe_select.setToolTip(_translate("pyCode", "[Ctrl+Q]查詢條件列表"))
        self.qbe_select.setShortcut(_translate("pyCode", "Ctrl+Q"))
        self.qbe_save.setText(_translate("pyCode", "條件儲存"))
        self.qbe_save.setToolTip(_translate("pyCode", "[Ctrl+W]查詢條件儲存"))
        self.qbe_save.setShortcut(_translate("pyCode", "Ctrl+W"))
        self.first.setText(_translate("pyCode", "第一筆"))
        self.first.setToolTip(_translate("pyCode", "[f]移到第一筆資料"))
        self.first.setShortcut(_translate("pyCode", "F"))
        self.previous.setText(_translate("pyCode", "上筆"))
        self.previous.setToolTip(_translate("pyCode", "[p]移到上一筆資料"))
        self.previous.setShortcut(_translate("pyCode", "P"))
        self.jump.setText(_translate("pyCode", "指定筆"))
        self.jump.setToolTip(_translate("pyCode", "[j]移到指定筆數資料"))
        self.jump.setShortcut(_translate("pyCode", "J"))
        self.next.setText(_translate("pyCode", "下筆"))
        self.next.setToolTip(_translate("pyCode", "[n]移到下一筆資料"))
        self.next.setShortcut(_translate("pyCode", "N"))
        self.last.setText(_translate("pyCode", "末一筆"))
        self.last.setToolTip(_translate("pyCode", "[l]移到最後一筆資料"))
        self.last.setShortcut(_translate("pyCode", "L"))
        self.key.setText(_translate("pyCode", "必要欄位"))
        self.key.setToolTip(_translate("pyCode", "[Ctrl+R]必須輸入的欄位清單"))
        self.key.setShortcut(_translate("pyCode", "Ctrl+R"))
        self.help.setText(_translate("pyCode", "說明"))
        self.help.setToolTip(_translate("pyCode", "[Ctrl+H]內容說明"))
        self.help.setShortcut(_translate("pyCode", "Ctrl+H"))
        self.exit.setText(_translate("pyCode", "離開"))
        self.exit.setToolTip(_translate("pyCode", "[Esc]離開程式"))
        self.exit.setShortcut(_translate("pyCode", "Esc"))
import pyCode_rc
